# Generated by Django 5.2.8 on 2026-01-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
