# Generated by Django 5.2.8 on 2025-12-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.course'),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.course'),
        ),
        migrations.AddField(
            model_name='notice',
            name='faculty_posted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facultyprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together={('student', 'course', 'mark_type')},
        ),
    ]
