# Generated by Django 5.2.8 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmark',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
