# Generated by Django 5.2.8 on 2025-12-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QAEntry',
        ),
    ]
