# Generated by Django 5.2.8 on 2025-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_delete_qaentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, help_text="Admin's reply to this feedback", null=True),
        ),
    ]
