# Generated by Django 5.2.8 on 2026-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_feedback_replied_at_feedback_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmark',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
