# Generated by Django 5.2.8 on 2026-01-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_internalmark_is_verified'),
        ('users', '0002_studentprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_feedbacks', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], default='ADMIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, help_text='Reply to this feedback', null=True),
        ),
    ]
