# Generated by Django 5.2.8 on 2026-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Notice will disappear after this time', null=True),
        ),
    ]
